#!/bin/sh

V=`grep "property name=\"version" build.xml | sed -e 's#^.*value="##' -e 's#".*$##'`
DD=gwtchismes-$V/doc
[ ! -d "$DD" ] && exit

D=gwtchismes-$V/gdocs
rm -rf  $D
mkdir -p $D || exit

find $DD -type f -exec cp '{}' $D ';' 

perl -pi -e 's#(href=|src=)"[^"]*/(.*?)"#$1"$2"#gi; s#on ... ... \d\d .*? 200.##g;' $D/*

#<!-- Generated by javadoc (build 1.6.0_10) on Fri Apr 03 09:11:38 CEST 2009 -->

# analitics="UA-645641-4"
analitics="UA-645641-6"

cat <<EOF >> $D/index.html
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "$analitics";
urchinTracker();
</script>
