#!/bin/sh

APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar" \
     com.google.gwt.i18n.tools.I18NSync \
     -out $APPDIR/src com.google.code.p.gwtcsample.client.GWTCSampleI18n
